
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=your_username
      - RABBITMQ_DEFAULT_PASS=your_password
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5


  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: "consul agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data"
    volumes:
      - consul-data:/consul/data
#    networks:
#      - consul-network

  pos-service:
    build: ./pos-service
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://your_username:your_password@rabbitmq:5672
      - CONSUL_URL=http://consul:8500
    depends_on:
      rabbitmq:
        condition: service_healthy

  kitchen-service:
    build: ./kitchen-service
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://your_username:your_password@rabbitmq:5672
      - CONSUL_URL=http://consul:8500
    depends_on:
      rabbitmq:
        condition: service_healthy

  fridge-service:
    build: ./fridge-service
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_URL=amqp://your_username:your_password@rabbitmq:5672
      - CONSUL_URL=http://consul:8500
    depends_on:
      rabbitmq:
        condition: service_healthy

  fridge-service-2:
    build: ./fridge-service
    ports:
      - "3004:3003"
    environment:
      - RABBITMQ_URL=amqp://your_username:your_password@rabbitmq:5672
      - CONSUL_URL=http://consul:8500
    depends_on:
      rabbitmq:
        condition: service_healthy

#
#  delivery-service:
#    build: ./delivery-service
#    ports:
#      - "3004:3004"
#    environment:
#      - RABBITMQ_URL=amqp://rabbitmq
#      - CONSUL_URL=http://consul:8500
#    depends_on:
#      - rabbitmq
#      - consul
#
#  reorder-service:
#    build: ./reorder-service
#    ports:
#      - "3005:3005"
#    environment:
#      - RABBITMQ_URL=amqp://rabbitmq
#      - CONSUL_URL=http://consul:8500
#    depends_on:
#      - rabbitmq
#      - consul
#
#  svelte-ui:
#    build: ./svelte-ui
#    ports:
#      - "5000:5000"
#    environment:
#      - WEBSOCKET_URL=ws://localhost:5000
#    depends_on:
#      - pos-service
#      - kitchen-service
#      - fridge-service
#      - delivery-service
#      - reorder-service

volumes:
  consul-data:


#services:
#  consul:
#    image: hashicorp/consul:latest
#    ports:
#      - "8500:8500"
#    command: "consul agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data"
#    volumes:
#      - consul-data:/consul/data
#    networks:
#      - consul-network
#
#  web:
#    image: nginx:latest
#    depends_on:
#      - consul
#    environment:
#      - CONSUL_HTTP_ADDR=consul:8500
#    command: >
#      sh -c "
#        while ! curl -s http://consul:8500/v1/agent/service/register -d '{\"Name\": \"web\", \"Address\": \"web\", \"Port\": 80}'; do
#          echo 'Waiting for Consul...';
#          sleep 2;
#        done;
#        nginx -g 'daemon off;'
#      "
#    networks:
#      - consul-network
#
#  api:
#    image: hashicorp/http-echo:latest
#    depends_on:
#      - consul
#    environment:
#      - CONSUL_HTTP_ADDR=consul:8500
#    command: >
#      sh -c "
#        while ! curl -s http://consul:8500/v1/agent/service/register -d '{\"Name\": \"api\", \"Address\": \"api\", \"Port\": 5678}'; do
#          echo 'Waiting for Consul...';
#          sleep 2;
#        done;
#        http-echo -listen=:5678 -text='Hello from API'
#      "
#
#  api2:
#    image: hashicorp/http-echo:latest
#    depends_on:
#      - consul
#    environment:
#      - CONSUL_HTTP_ADDR=consul:8500
#    command: >
#      sh -c "
#        echo ggg
#      "
#    networks:
#      - consul-network
#
#
#
#volumes:
#  consul-data:
#
#networks:
#  consul-network:
#    driver: bridge
#
#

